name: backend

on:
  push:
    branches:
      - development
      - main
    paths:
      - backend/**
      - .github/workflows/backend.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.ACR_LOGIN_SERVER }}
        username: ${{ vars.ACR_USER_NAME }}
        password: ${{ secrets.ACR_USER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd ./backend
        docker build -t ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.BE_IMAGE_NAME }}:${{ github.run_number }} .
        docker push ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.BE_IMAGE_NAME }}:${{ github.run_number }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.BE_APP_NAME }}
        images: ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.BE_IMAGE_NAME }}:${{ github.run_number }}

    - name: Add SCM_DO_BUILD_DURING_DEPLOYMENT setting
      run: |
        az webapp config appsettings set --name ${{ vars.BE_APP_NAME }} \
          --resource-group ${{ vars.RG_NAME }} \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

# END ---------------------------------------