# Make changes in - NAME, BRANCH, MODULE_DIR_PATH (if applicable), KEY, VALUE

on:
  push:
    branches:
      - development
      - main
      - BRANCH
    paths:
      - MODULE_DIR_PATH/**
      - .github/workflows/NAME.yml

env:
  # For pipeline debugging purposes.
  ACTIONS_STEP_DEBUG: ${{ vars.ACTIONS_STEP_DEBUG }}  

  # ENV
  KEY1: ${{ vars.KEY1 }}
  KEY2: VALUE2
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: MODULE_DIR_PATH

      # Uncomment the following lines if you want to run tests
      # - name: Run tests
      #   run: npm test
      #   working-directory: MODULE_DIR_PATH

      - name: Build application
        run: |
          npm run build
        working-directory: MODULE_DIR_PATH

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ vars.AZURE_SWA_APP_NAME_DEPLOYMENT_TOKEN }}
          action: "upload"
          app_location: "MODULE_DIR_PATH"
          output_location: "build" 

# END  -----------------------------------------
